/* INVTOOL local-first application shell. Live API calls are isolated behind /api/request. */
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const catalog=[
 {icon:'🪓',name:'Thunder Shotgun',type:'Weapon',rarity:'Epic',path:'/Game/Weapons/Shotguns/ThunderShotgun',mods:['Default template','Extended Mag','Stabilized']},
 {icon:'⚔️',name:'Energy Blade',type:'Weapon',rarity:'Legendary',path:'/Game/Weapons/Melee/EnergyBlade',mods:['Default template','Overcharged','Vampiric']},
 {icon:'🎯',name:'Reaper Rifle',type:'Weapon',rarity:'Rare',path:'/Game/Weapons/Rifles/Reaper',mods:['Default template','Precision','Quickdraw']},
 {icon:'🧪',name:'Shield Potion',type:'Consumable',rarity:'Uncommon',path:'/Game/Items/Consumables/ShieldPotion',mods:['Default template']},
 {icon:'💣',name:'Shockwave Grenade',type:'Consumable',rarity:'Epic',path:'/Game/Items/Grenades/Shockwave',mods:['Default template']},
 {icon:'🔫',name:'Tactical Pistol',type:'Weapon',rarity:'Common',path:'/Game/Weapons/Pistols/Tactical',mods:['Default template','Quickdraw']},
 {icon:'🛡️',name:'Overshield',type:'Device',rarity:'Rare',path:'/Game/Items/Devices/Overshield',mods:['Default template']},
 {icon:'🔋',name:'Med Kit',type:'Consumable',rarity:'Uncommon',path:'/Game/Items/Consumables/MedKit',mods:['Default template']},
 {icon:'🎨',name:'Midnight Bloom',type:'Wrap',rarity:'Legendary',path:'/Game/Cosmetics/Wraps/MidnightBloom',mods:['Default template']},
 {icon:'✨',name:'Carbon Fiber',type:'Wrap',rarity:'Epic',path:'/Game/Cosmetics/Wraps/CarbonFiber',mods:['Default template']}
];
const islands=[{name:'The Citadel Trials',state:'LIVE',updated:'2h ago',players:'1,248',accent:'blue'},{name:'Neon Drift Arena',state:'DRAFT',updated:'yesterday',players:'—',accent:'pink'},{name:'Wildwood Survival',state:'LIVE',updated:'4d ago',players:'392',accent:'green'}];
const state={view:'overview',connected:false,selectedIsland:0,filter:'All',assetQuery:'',inventory:JSON.parse(localStorage.getItem('invtool.inventory')||'null')||catalog.slice(0,8).map((item,i)=>({...item,quantity:[3,1,2,5,4,1,1,2][i],mod:item.mods[0],wrap:'None',selected:false})),undo:[],redo:[],dirty:false};
function toast(message,kind='info'){const t=$('#toast');t.textContent=message;t.dataset.kind=kind;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
function pageHead(kicker,title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1 class="headline">${title}</h1><p class="sub">${sub}</p></div><div class="page-actions">${actions}</div></div>`}
function islandCards(){return `<div class="island-grid">${islands.map((x,i)=>`<button class="card island ${x.accent}" data-island="${i}"><div class="island-body"><span class="pill">${x.state}</span><h3>${x.name}</h3><p>${x.players} active players · Updated ${x.updated}</p></div></button>`).join('')}</div>`}
function stats(){return `<div class="grid"><div class="stat"><div class="stat-label">Connected islands</div><div class="stat-value">${state.connected?3:'—'}</div><div class="stat-foot">${state.connected?'Synced just now':'Connect a service to begin'}</div></div><div class="stat"><div class="stat-label">Persistence records</div><div class="stat-value">2,481</div><div class="stat-foot"><span class="up">↑ 8.4%</span> this week</div></div><div class="stat"><div class="stat-label">Asset index</div><div class="stat-value">148k+</div><div class="stat-foot">Paths ready to search</div></div></div>`}
function renderOverview(){return pageHead('CREATOR WORKSPACE','Persistence, without the friction.','Inspect islands, find assets by full path, and make precise inventory edits.','<button class="primary" data-action="connect">Connect service <span>↗</span></button>')+stats()+`<div class="section-title"><h2>Recent islands</h2><button class="secondary" data-view="maps">View all →</button></div>${islandCards()}<div class="section-title"><h2>Quick actions</h2></div><div class="quick-grid"><button class="card quick" data-view="inventory"><b>▦</b><strong>Open inventory editor</strong><small>Stage item, mod, and wrap changes</small></button><button class="card quick" data-view="assets"><b>⌕</b><strong>Search content catalog</strong><small>Find assets by any path fragment</small></button><button class="card quick" data-action="export"><b>↓</b><strong>Export workspace</strong><small>Download a portable JSON snapshot</small></button></div>`}
function renderMaps(){return pageHead('ISLANDS','Your islands','Choose an island to open its persistence data.','<button class="outline-btn" data-action="connect">↻ Sync islands</button>')+`<div class="toolbar"><input class="search" placeholder="Search islands…" /><span class="muted">${islands.length} islands indexed</span></div>${islandCards()}`}
function assetRows(){const q=state.assetQuery.toLowerCase();const rows=catalog.filter(a=>(a.name+a.path+a.type+a.rarity).toLowerCase().includes(q)&& (state.filter==='All'||a.type===state.filter));return rows.length?rows.map(a=>`<div class="asset"><div class="asset-icon ${a.rarity.toLowerCase()}">${a.icon}</div><div><strong>${a.name}</strong><small>${a.type} · ${a.rarity}</small></div><span class="asset-path">${a.path}</span><button class="secondary" data-copy="${a.path}">Copy</button></div>`).join(''):'<div class="empty"><b>⌕</b><strong>No assets found</strong><span>Try a different name, type, or path fragment.</span></div>'}
function renderAssets(){const types=['All',...new Set(catalog.map(a=>a.type))];return pageHead('ASSET BROWSER','Find anything by path.','Search the indexed content catalog. No premade dropdowns — use the path you know.')+`<div class="card"><div class="row"><input id="asset-search" class="search" value="${state.assetQuery}" placeholder="Search asset name or /Game/ path…" autofocus /><span class="tag">PATH INDEX</span></div><div class="filter-row">${types.map(x=>`<button class="filter ${state.filter===x?'chosen':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="asset-list">${assetRows()}</div></div>`}
function renderInventory(){const active=state.inventory.find(x=>x.selected)||state.inventory[0];return pageHead('INVENTORY EDITOR','Edit persistence records',`${islands[state.selectedIsland].name} · Player profile · ${state.dirty?'Unsaved changes':'Saved locally'}`,`<button class="secondary" data-action="undo" ${!state.undo.length?'disabled':''}>↶ Undo</button><button class="primary" data-action="save">${state.dirty?'Save changes':'Saved ✓'}</button>`)+`<div class="inventory-grid"><div class="card"><div class="row-between"><h3>Items <span class="pill">${state.inventory.length} total</span></h3><div class="row"><input class="mini-search" id="item-search" placeholder="Filter items…" /><button class="secondary" data-action="add">+ Add</button></div></div><div class="item-grid">${state.inventory.map((x,i)=>`<button class="item ${x.selected?'selected':''}" data-item="${i}"><div class="item-art">${x.icon}</div><strong>${x.name}</strong><small>${x.quantity} × ${x.rarity}</small></button>`).join('')}</div></div><div class="card inspector"><h3>Item properties</h3>${active?`<div class="selected-name"><span class="item-art">${active.icon}</span><div><strong>${active.name}</strong><small>${active.path}</small></div></div><div class="control"><label>QUANTITY</label><input class="search" id="quantity" type="number" min="0" max="999" value="${active.quantity}" /></div><div class="control"><label>ITEM MOD / TEMPLATE ID</label><select class="select" id="mod">${active.mods.map(m=>`<option ${active.mod===m?'selected':''}>${m}</option>`).join('')}</select></div><div class="control"><label>WRAP</label><select class="select" id="wrap">${['None','Carbon Fiber','Midnight Bloom'].map(m=>`<option ${active.wrap===m?'selected':''}>${m}</option>`).join('')}</select></div><button class="primary full" data-action="apply">Apply to selected item</button><button class="secondary full" data-action="delete">Remove item</button>`:'<div class="empty">Select an item to inspect it.</div>'}</div></div>`}
function renderSettings(){return pageHead('PREFERENCES','Settings','Configure your local workspace and service connection.')+`<div class="settings-grid"><div class="card"><h3>Service connection</h3><p class="sub">Tokens remain in memory and are sent only through the local proxy.</p><button class="primary" data-action="connect">${state.connected?'Reconnect service':'Open connection dialog'}</button></div><div class="card"><h3>Workspace data</h3><p class="sub">Inventory edits are saved to this browser’s local storage.</p><button class="secondary" data-action="clear">Reset local inventory</button></div></div>`}
function render(){const views={overview:renderOverview,maps:renderMaps,assets:renderAssets,inventory:renderInventory,settings:renderSettings};$('#app').innerHTML=views[state.view]();$('#page-name').textContent=state.view[0].toUpperCase()+state.view.slice(1);$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view));bind()}
function snapshot(){state.undo.push(JSON.stringify(state.inventory));if(state.undo.length>30)state.undo.shift();state.redo=[];state.dirty=true}
function bind(){
 $$('[data-view]').forEach(x=>x.onclick=()=>{state.view=x.dataset.view;render()});
 $$('[data-island]').forEach(x=>x.onclick=()=>{state.selectedIsland=+x.dataset.island;state.view='inventory';render()});
 $$('[data-filter]').forEach(x=>x.onclick=()=>{state.filter=x.dataset.filter;render()});
 const search=$('#asset-search');if(search){search.oninput=e=>{state.assetQuery=e.target.value;const list=$('.asset-list');list.innerHTML=assetRows()};}
 $$('[data-copy]').forEach(x=>x.onclick=async()=>{await navigator.clipboard?.writeText(x.dataset.copy);toast('Asset path copied','success')});
 const itemSearch=$('#item-search');if(itemSearch)itemSearch.oninput=e=>$$('.item', $('#app')).forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase()));
 $$('[data-item]').forEach(x=>x.onclick=()=>{state.inventory.forEach(i=>i.selected=false);state.inventory[+x.dataset.item].selected=true;render()});
 $$('[data-action]').forEach(x=>x.onclick=()=>action(x.dataset.action));
}
function action(a){if(a==='connect')return openModal();if(a==='add'){snapshot();state.inventory.push({...catalog[0],quantity:1,mod:catalog[0].mods[0],wrap:'None',selected:true});state.inventory.forEach((x,i)=>x.selected=i===state.inventory.length-1);render();return}if(a==='delete'){if(state.inventory.length<=1)return toast('Keep at least one item');snapshot();state.inventory=state.inventory.filter(x=>!x.selected);state.inventory[0].selected=true;render();return}if(a==='apply'){const i=state.inventory.find(x=>x.selected);if(i){snapshot();i.quantity=+$('#quantity').value;i.mod=$('#mod').value;i.wrap=$('#wrap').value;render();toast('Item changes staged','success')}return}if(a==='save'){localStorage.setItem('invtool.inventory',JSON.stringify(state.inventory));state.dirty=false;render();toast('Workspace saved locally','success');return}if(a==='undo'&&state.undo.length){state.redo.push(JSON.stringify(state.inventory));state.inventory=JSON.parse(state.undo.pop());state.dirty=true;render();return}if(a==='export'){const blob=new Blob([JSON.stringify({island:islands[state.selectedIsland],inventory:state.inventory},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='invtool-persistence.json';a.click();URL.revokeObjectURL(url);toast('Persistence JSON exported','success');return}if(a==='clear'){localStorage.removeItem('invtool.inventory');state.inventory=catalog.slice(0,8).map((item,i)=>({...item,quantity:i+1,mod:item.mods[0],wrap:'None',selected:i===0}));render();toast('Local inventory reset')}}
function openModal(){$('#modal').classList.add('open')}$('#connect-open').onclick=openModal;$('#modal-close').onclick=()=>$('#modal').classList.remove('open');$('#connect').onclick=async()=>{const btn=$('#connect'),endpoint=$('#endpoint').value.replace(/\/$/,''),token=$('#token').value.trim();if(!token)return toast('A session token is required');btn.disabled=true;btn.textContent='Connecting…';try{const r=await fetch('/api/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:endpoint+'/inventory',token,body:{}})});if(!r.ok)throw Error('Service returned '+r.status);state.connected=true;$('#modal').classList.remove('open');$('#connection-title').textContent='Service connected';$('#connection-copy').textContent='Session active · memory only';$('.status-dot').style.background='#48d7af';toast('Service connected successfully','success');render()}catch(e){toast('Could not connect: '+e.message)}finally{btn.disabled=false;btn.innerHTML='Connect & load islands <span>→</span>'}};$('#logout').onclick=()=>{state.connected=false;$('#connection-title').textContent='Not connected';$('.status-dot').style.background='#66758a';$('#token').value='';toast('Local session cleared');render()};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('open');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(state.view==='inventory')action('save')}});render();
