const http=require('http'),fs=require('fs'),path=require('path'),{URL}=require('url');
const PORT=process.env.PORT||4173, ROOT=__dirname;
const allowedHost=process.env.CONTENT_SERVICE_HOST||'content-service.bfda.live.use1a.on.epicgames.com';
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
function send(res,status,data,type='application/json'){res.writeHead(status,{'content-type':type,'access-control-allow-origin':'*','cache-control':'no-store'});res.end(type==='application/json'?JSON.stringify(data):data)}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-session-token'});return res.end()}
 if(req.url.startsWith('/api/request')){if(!['GET','POST','PUT','PATCH','DELETE'].includes(req.method))return send(res,405,{error:'Method not allowed'});const b=await body(req);const target=b.url||req.headers['x-target-url'];if(!target)return send(res,400,{error:'Missing target URL'});let u;try{u=new URL(target)}catch{return send(res,400,{error:'Invalid URL'})}if(u.protocol!=='https:'||u.hostname!==allowedHost)return send(res,403,{error:`Only https://${allowedHost} is allowed`});const headers={'accept':'application/json','user-agent':'INVTOOL/1.0'};const token=b.token||req.headers['x-session-token'];if(token)headers.authorization=token.toLowerCase().startsWith('bearer ')?token:`Bearer ${token}`;if(req.method!=='GET')headers['content-type']='application/json';const upstream=await fetch(u,{method:req.method,headers,body:req.method==='GET'?undefined:JSON.stringify(b.body||{})});const text=await upstream.text();res.writeHead(upstream.status,{'content-type':upstream.headers.get('content-type')||'application/json','cache-control':'no-store'});return res.end(text)}
 let requested=req.url.split('?')[0];if(requested==='/'||requested===''||(!path.extname(requested)&&req.method==='GET'))requested='/index.html';const file=path.normalize(path.join(ROOT,requested));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return send(res,404,{error:'Not found'});send(res,200,fs.readFileSync(file),mime[path.extname(file)]||'application/octet-stream')
}catch(e){send(res,502,{error:e.message||'Upstream request failed'})}});server.listen(PORT,'0.0.0.0',()=>console.log(`INVTOOL listening on 0.0.0.0:${PORT}`));
